# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 202db342a19c13de5ca5cc74d821353ac9c1b449e532e58f7e45f91f012020eddd97e6c1f8fde748cf2d10e129b979b019604dcf97fb827173068e6bc4d856e6

test:
  secret_key_base: 73f94a22679ce1dad5ed2add8cdf888a167e73dbc5c75cef6a98300745abdc770a57d72d7c0c7086b05ace75dd1e01b129a17918ac596bbbb9d825b3751037ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
